rootProject.name = "PapaKarlo"
include(":common")
include(":presentation")
include(":domain")
include(":app")
include(":domain_api")
include(":data_api")
include(":data")
include(":shared")
//include(":data_firebase")
//include(":domain_firebase")