default_platform(:ios)

platform :ios do
  before_all do
    # Выбираем версию Xcode для сборки
    xcodes(version: "26.4", select_for_current_build_only: true)

    # App Store Connect API Key
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_P8_PATH']
    )
  end

  # Список приложений с идентификатором и схемой
  apps = {
     papakarlo:    { id: "com.bunbeuaty.papakarlo", scheme: "papakarlo" },
     gustopub:     { id: "com.bunbeauty.gustopub", scheme: "gustoPub" },
     yuliar:       { id: "com.bunbeauty.yuliar", scheme: "yuliar" },
     tandirhouse:  { id: "com.bunbeauty.tandirhouse", scheme: "tandirhouse" },
     vkuskavkaza:  { id: "com.bunbeauty.vkuskavkaza", scheme: "vkuskavkaza" },
     djan:         { id: "com.bunbeauty.djan", scheme: "djan" },
     usaba:        { id: "com.bunbeauty.usadba", scheme: "usadba" },
     emoji:        { id: "com.bunbeauty.emoji", scheme: "emoji" },
     estpoest:     { id: "com.bunbeauty.estpoest", scheme: "estpoest" },
     taverna:      { id: "com.bunbeauty.taverna", scheme: "taverna" },
     voljane:      { id: "com.bunbeauty.voljane", scheme: "voljane" },
     legenda:      { id: "com.bunbeauty.legenda", scheme: "legenda" },
     bereg:      { id: "com.bunbeauty.bereg", scheme: "bereg" },
     bereg:      { id: "com.bunbeauty.mimino", scheme: "mimino" },
  }

  # Универсальная функция сборки и заливки
  def build_and_upload(app_identifier, scheme)
    # Уникальный build number для TestFlight на CI
    if ENV["GITHUB_RUN_NUMBER"]
      increment_build_number(
        xcodeproj: "iosApp.xcodeproj",
        build_number: ENV["GITHUB_RUN_NUMBER"]
      )
    end

    # Подтягиваем сертификаты/профили для конкретного bundle id (readonly на CI)
    match(
      type: "appstore",
      app_identifier: app_identifier,
      readonly: (ENV["MATCH_READONLY"] == "true")
    )

    build_app(
      workspace: "iosApp.xcworkspace",
      scheme: scheme,
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          app_identifier => "match AppStore #{app_identifier}"
        }
      }
    )

    upload_to_testflight(
      app_identifier: app_identifier,
      skip_waiting_for_build_processing: true
    )

#     deliver(
#       submit_for_review: true,
#       automatic_release: false,
#       skip_screenshots: true,
#       force: true,
#       skip_metadata: true,
#       precheck_include_in_app_purchases: false,
#       release_notes: {
#         "ru" => "Исправлены ошибки и улучшена стабильность."
#       },
#       submission_information: {
#         export_compliance_uses_encryption: false,
#         export_compliance_encryption_updated: false
#       }
#     )
  end

  # Динамическая генерация lane для каждого приложения
  apps.each do |lane_name, config|
    desc "Push a new #{lane_name} release build to the App Store"
    lane lane_name do
      build_and_upload(config[:id], config[:scheme])
    end
  end

  # Lane для деплоя всех приложений
  desc "Deploy all apps to TestFlight"
  lane :deployAll do
    apps.keys.each do |app|
      send(app)
    end
  end
end
