source "https://cdn.cocoapods.org"
use_frameworks!
use_modular_headers!

platform :ios, '14.1'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
  
  pod 'Firebase', '~> 9.5.0'
  pod 'Firebase/Analytics', '~> 9.5.0'
  pod 'Firebase/Crashlytics', '~> 9.5.0'
  pod 'FirebaseCore', '~> 9.5.0'
  pod 'GoogleUtilities'
  pod 'FirebaseAuth', '~> 9.5.0'
  pod 'Kingfisher'
  pod 'shared', :path => '../shared'
end
