source "https://cdn.cocoapods.org"
use_frameworks!
use_modular_headers!

platform :ios, '14.1'

install! 'cocoapods', :deterministic_uuids => false

def default_pods
  pod 'Firebase', '~> 9.5.0'
  pod 'Firebase/Analytics', '~> 9.5.0'
  pod 'Firebase/Crashlytics', '~> 9.5.0'
  pod 'FirebaseCore', '~> 9.5.0'
  pod 'FirebaseMessaging', '~> 9.5.0'
  pod 'GoogleUtilities'
  pod 'Kingfisher'
  pod 'shared', :path => '../shared'
end

target 'papakarlo' do
  default_pods
end

target 'yuliar' do
  default_pods
end

target 'djan' do
  default_pods
end

target 'gustopub' do
  default_pods
end
