name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

on: [ push ]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON > app/google-services.json
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Download APK Debug - ${{ env.repository_name }}
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

  check_lint_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: check android lint
        run: ./gradlew --continue :app:lint
  check_ktLint_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: check ktLint
        run: ./gradlew --continue ktlintCheck

#  unit_tests_job:
#    runs-on: ubuntu-latest
#    needs: [job1, job2]
#    steps:
#    - name: check unit tets
#      run: todo