name: Android CI

on: [ pull_request:
        - 'develop' ]


jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON > app/google-services.json
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assembleDebug

  check_lint_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - uses: actions/checkout@v2

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON > app/google-services.json
      - name: check android lint
        run: ./gradlew --continue :app:lint
  check_ktLint_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - uses: actions/checkout@v2
      - name: check ktLint
        run: ./gradlew --continue ktlintCheck

#  unit_tests_job:
#    runs-on: ubuntu-latest
#    needs: [job1, job2]
#    steps:
#    - name: check unit tets
#      run: todo