name: Android CI

on: [push]

stages:
  - build
  - checking
  - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE_JSON > app/google-services.json
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assembleDebug
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - name: check ktLint
      run: ./gradlew --continue ktlintCheck
    - name: check android lint
      run: ./gradlew --continue :app:lint
