name: "Pull request workflow"

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.event.pull_request.number }}-pull-request
  cancel-in-progress: true

jobs:
  setup:
    name: "Upload secrets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Decode google-services.json"
        env:
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo "${GOOGLE_SERVICE_JSON}" > app/google-services.json
      - name: "Upload google-services.json"
        uses: actions/upload-artifact@v4
        with:
          name: google-services
          path: app/google-services.json
      - name: "Decode build config"
        env:
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: echo -e "RELEASE_STORE_FILE=$RELEASE_STORE_FILE
          \nRELEASE_STORE_PASSWORD=$RELEASE_STORE_PASSWORD
          \nRELEASE_KEY_ALIAS=$RELEASE_KEY_ALIAS
          \nRELEASE_KEY_PASSWORD=$RELEASE_KEY_PASSWORD" > local.properties
      - name: "Upload local.properties"
        uses: actions/upload-artifact@v4
        with:
          name: local-properties
          path: local.properties

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        flavor: [ "papakarlo", "yuliar", "djan", "gustopub", "tandirhouse", "vkuskavkaza" ]
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Upload google-services.json"
        uses: actions/download-artifact@v4
        with:
          name: google-services
          path: ./app
      - name: "Upload local.properties"
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .
      - name: "Assemble ${{ matrix.flavor }}"
        run: ./gradlew --continue assemble${{ matrix.flavor }}Debug

  linter:
    name: "Linter"
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        linter: [ "lint", "ktLint" ]
        flavor: [ "papakarlo", "yuliar", "djan", "gustopub", "tandirhouse", "vkuskavkaza" ]
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Upload google-services.json"
        uses: actions/download-artifact@v4
        with:
          name: google-services
          path: ./app
      - name: "Upload local.properties"
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .
      - name: "Lint ${{ matrix.flavor }}"
        if: ${{ matrix.linter == 'lint' }}
        run: ./gradlew --continue lint${{ matrix.flavor }}Debug
      - name: "KtLint ${{ matrix.flavor }}"
        if: ${{ matrix.linter == 'ktLint' }}
        run: ./gradlew --continue ktLint${{ matrix.flavor }}DebugCheck

  test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Upload google-services.json"
        uses: actions/download-artifact@v4
        with:
          name: google-services
          path: ./app
      - name: "Upload local.properties"
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .
      - name: "Run unit tests"
        run: ./gradlew test